import os
import pyautogui

# num = 1
# end_num = 7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
# a=1
local = 'D:/picture1/'
pic = os.listdir(local)
for i in pic:
	os.system("adb -s a333ba7a0321 push"+' '+local+i+' '+ "/sdcard/DCIM/Camera/")
# for i in range(num,end_num):
# 	os.system("adb push D://picture1/1(%s).jpg /sdcard/DCIM/Camera/"%(a))
# 	a+=1