// Generated by CoffeeScript 1.12.7
(function() {
  var Hs, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.Hs || (root.Hs = {});

  Hs = root.Hs;

  root.num = 0;

  $(function() {
    var add_tr, load_comments;
    console.log("local demo puco");
    add_tr = function(content_json) {
      var error, kol, redId;
      kol = content_json["data"];
      try {
        redId = kol["redId"];
      } catch (error1) {
        error = error1;
        console.log("error", kol);
        return;
      }
      if ($("#xhs_" + redId).length < 1) {
        root.num = root.num + 1;
        return $(".a").append("<tr style=\"margin:10px;\" id=\"xhs_" + redId + "\">\n    <td>" + num + "</td>\n    <td>" + kol["redId"] + "</td>\n    <td>" + kol["name"] + "</td>\n    <td>" + kol["currentLevel"] + "</td>\n    <td>" + ((parseInt(kol["likeCollectCountInfo"]) / parseInt(kol["totalNoteCount"])).toFixed(2)) + "</td>\n    <td>" + kol["likeCollectCountInfo"] + "</td>\n    <td>" + kol["totalNoteCount"] + "</td>\n    <td>" + kol["fansCount"] + "</td>\n    <td>" + kol["businessNoteCount"] + "</td>\n    <td>" + kol["userId"] + "</td>\n    <td>\n        <div><a target=\"_blank\" href=\"https://www.xiaohongshu.com/user/profile/" + kol["userId"] + "\">" + kol["userId"] + "</a></div>\n    </td>\n    <td>\n        <div><a target=\"_blank\" href=\"https://pgy.xiaohongshu.com/solar/advertiser/kol/" + kol["userId"] + "\">" + kol["userId"] + "</a></div>\n    </td>\n    <td>" + kol["picturePrice"] + "</td>\n    <td>" + kol["videoPrice"] + "</td>\n</tr>");
      }
    };
    load_comments = function(chat_id, comment_id) {
      if (chat_id == null) {
        chat_id = null;
      }
      if (comment_id == null) {
        comment_id = null;
      }
      if (chat_id === null) {
        return;
      }
      return $.ajax({
        url: "https://www.qianshanghua.com/api/page/comment/load",
        data: {
          chat_id: chat_id,
          comment_id: comment_id
        },
        dataType: "json",
        type: "GET",
        success: function(data) {
          var add_tr_next, comments, content_json, error, i, last_comment_id, len, one;
          comments = data.comments;
          for (i = 0, len = comments.length; i < len; i++) {
            one = comments[i];
            if (one[4] === "v") {
              continue;
            }
            add_tr_next = false;
            try {
              content_json = JSON.parse(one[4]);
              add_tr_next = true;
            } catch (error1) {
              error = error1;
              add_tr_next = false;
            }
            if (add_tr_next) {
              add_tr(content_json);
            }
          }
          console.log(chat_id, comment_id, data.last_comment_id);
          last_comment_id = data.last_comment_id;
          if (data.last_comment_id !== null) {
            return load_comments(chat_id, last_comment_id);
          }
        },
        error: function(data) {
          return console.log(data);
        }
      });
    };
    return $(window).on("load", function(e) {
      $(".a").append("<tr style=\"margin:10px;\">\n    <th>编号</th>\n    <th>小红书号</th>\n    <th>昵称</th>\n    <th>level</th>\n    <th>均篇点赞收藏</th>\n    <th>点赞收藏</th>\n    <th>笔记数</th>\n    <th>粉丝数</th>\n    <th>商业笔记</th>\n    <th>userId</th>\n    <th>个人主页</th>\n    <th>蒲公英主页</th>\n    <th>笔记图文一口价</th>\n    <th>视频图文一口价</th>\n</tr>");
      return load_comments("e26d371b9b614acf8bb57198af09f0a2");
    });
  });

}).call(this);
